package com.egangotri.monierWilliams.dao.vo;

// Generated Jun 23, 2007 7:20:04 PM by Hibernate Tools 3.1.0.beta5

/**
 * WordMaster generated by hbm2java
 */
public class WordMaster implements java.io.Serializable
{

    // Fields

    private int    id;

    /** This is in IAST by default */
    private String word;

    private String meaning = null;

    private String wordInSLP;
    
    private String wordinItrans;
    
    private String wordinDVN;
    // Constructors

    /** default constructor */
    public WordMaster()
    {
    }

    /** minimal constructor */
    public WordMaster(int id, String word)
    {
        this.id = id;
        this.word = word;
    }

    /** full constructor */
    public WordMaster(int id, String word,  String meaning)
    {
        this.id = id;
        this.word = word;
        this.meaning = meaning;
    }

    // Property accessors
    public int getId()
    {
        return this.id;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public String getWord()
    {
        return this.word;
    }

    public void setWord(String word)
    {
        this.word = word;
    }



    public String getMeaning()
    {
        return this.meaning;
    }

    public void setMeaning(String meaning)
    {
        this.meaning = meaning;
    }

    public String getWordInSLP()
    {
        return wordInSLP;
    }

    public void setWordInSLP(String wordInSLP)
    {
        this.wordInSLP = wordInSLP;
    }

    public String getWordinItrans()
    {
        return wordinItrans;
    }

    public void setWordinItrans(String wordinItrans)
    {
        this.wordinItrans = wordinItrans;
    }

    public String getWordinDVN()
    {
        return wordinDVN;
    }

    public void setWordinDVN(String wordinDVN)
    {
        this.wordinDVN = wordinDVN;
    }


}
